#!/bin/bash

# register gitlab-runner
gitlab-runner register

# present current config
cat /etc/gitlab-runner/config.toml

# launch gitlab-runner passing all arguments
gitlab-runner run --working-directory /home/gitlab-runner
