#!/bin/bash

[ -z "$CI_SERVER_URL" ] && echo "need to set CI_SERVER_URL" && exit 1
[ -z "$REGISTRATION_TOKEN" ] && echo "need to set REGISTRATION_TOKEN" && exit 1

export REGISTER_NON_INTERACTIVE=true

gitlab-runner register --executor docker --docker-image docker:latest --docker-volumes /var/run/docker.sock:/var/run/docker.sock
gitlab-runner run --working-directory /home/gitlab-runner
